pub mod actor;
pub mod assets;
pub mod contracts;
pub mod diagnostics;
pub mod file_contracts;
pub mod files;
pub mod presentation;
pub mod runtime;
pub mod security;
pub mod server;
pub mod state;

use crate::commands::{CommandId, IconId};
use contracts::{ThemeView, WFE_PROTOCOL_VERSION};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;

pub const WFE_PROTOCOL_V6_SCHEMA_SHA256: &str =
    "915a1efd4bf273a17db628dd0f552bdb02c79cc42d8eaa5290e66d6fed2a4328";

pub fn protocol_schema_sha256() -> String {
    let digest = Sha256::digest(contracts::typescript_declarations().as_bytes());
    let mut hash = String::with_capacity(digest.len() * 2);
    for byte in digest {
        write!(hash, "{byte:02x}").expect("writing to a String cannot fail");
    }
    hash
}

pub fn generated_typescript_source() -> Result<String, String> {
    let command_order = CommandId::ALL
        .iter()
        .map(|command| serde_json::to_value(command).map_err(|error| error.to_string()))
        .collect::<Result<Vec<_>, _>>()?;
    let icon_ids = IconId::ALL
        .iter()
        .map(|icon| serde_json::to_value(icon).map_err(|error| error.to_string()))
        .collect::<Result<Vec<_>, _>>()?;
    let icon_glyphs = IconId::ALL
        .iter()
        .map(|icon| {
            let id = serde_json::to_value(icon).map_err(|error| error.to_string())?;
            let id = id
                .as_str()
                .ok_or_else(|| "serialized icon ID was not a string".to_string())?;
            Ok((id.to_string(), icon.glyph().to_string()))
        })
        .collect::<Result<std::collections::BTreeMap<_, _>, String>>()?;
    let mut ui_icon_glyphs = std::collections::BTreeMap::new();
    let mut seen_ui_glyphs = std::collections::BTreeSet::new();
    for &(id, glyph) in crate::icons::WFE_UI_ICONS {
        if id.is_empty()
            || id.starts_with('-')
            || id.ends_with('-')
            || !id
                .bytes()
                .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
        {
            return Err(format!("invalid WFE UI icon ID `{id}`"));
        }
        if glyph.chars().count() != 1 {
            return Err(format!("WFE UI icon `{id}` must contain exactly one glyph"));
        }
        if ui_icon_glyphs
            .insert(id.to_string(), glyph.to_string())
            .is_some()
        {
            return Err(format!("duplicate WFE UI icon ID `{id}`"));
        }
        if !seen_ui_glyphs.insert(glyph) {
            return Err(format!("duplicate WFE UI icon glyph for `{id}`"));
        }
    }
    for (name, frames) in [
        ("spinner", crate::icons::SPINNER),
        ("tool spinner", crate::icons::TOOL_SPINNER),
    ] {
        if frames.is_empty()
            || frames.len() > 16
            || frames.iter().any(|frame| {
                frame.is_empty() || frame.chars().count() > 4 || frame.chars().any(char::is_control)
            })
        {
            return Err(format!("invalid WFE {name} frames"));
        }
    }
    let themes: Vec<ThemeView> = presentation::theme_catalog();

    let mut source = String::from(
        "// This file is generated by `cargo run --bin generate_web_contracts`.\n\
         // Do not edit it by hand.\n\n",
    );
    source.push_str(&contracts::typescript_declarations());
    source.push_str(&format!(
        "export const WFE_PROTOCOL_VERSION = {WFE_PROTOCOL_VERSION} as const;\n\n"
    ));
    source.push_str(&format!(
        "export const WFE_PROTOCOL_SCHEMA_SHA256 = {} as const;\n\n",
        serde_json::to_string(&protocol_schema_sha256()).map_err(|error| error.to_string())?
    ));
    source.push_str("export const COMMAND_ORDER = ");
    source.push_str(
        &serde_json::to_string_pretty(&command_order).map_err(|error| error.to_string())?,
    );
    source.push_str(" as const satisfies readonly CommandId[];\n\n");
    source.push_str("export const ICON_IDS = ");
    source.push_str(&serde_json::to_string_pretty(&icon_ids).map_err(|error| error.to_string())?);
    source.push_str(" as const satisfies readonly IconId[];\n\n");
    source.push_str("export const ICON_GLYPHS = ");
    source
        .push_str(&serde_json::to_string_pretty(&icon_glyphs).map_err(|error| error.to_string())?);
    source.push_str(" as const satisfies Readonly<Record<IconId, string>>;\n\n");
    source.push_str("export const UI_ICON_GLYPHS = ");
    source.push_str(
        &serde_json::to_string_pretty(&ui_icon_glyphs).map_err(|error| error.to_string())?,
    );
    source.push_str(" as const;\n\n");
    source.push_str("export type UiIconId = keyof typeof UI_ICON_GLYPHS;\n\n");
    source.push_str("export const SPINNER_FRAMES = ");
    source.push_str(
        &serde_json::to_string(crate::icons::SPINNER).map_err(|error| error.to_string())?,
    );
    source.push_str(" as const;\n\n");
    source.push_str("export const TOOL_SPINNER_FRAMES = ");
    source.push_str(
        &serde_json::to_string(crate::icons::TOOL_SPINNER).map_err(|error| error.to_string())?,
    );
    source.push_str(" as const;\n\n");
    source.push_str("export const THEME_CATALOG = ");
    source.push_str(&serde_json::to_string_pretty(&themes).map_err(|error| error.to_string())?);
    source.push_str(" as const satisfies readonly ThemeView[];\n");
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_source_is_deterministic_and_allowlisted() {
        let first = generated_typescript_source().unwrap();
        let second = generated_typescript_source().unwrap();
        assert_eq!(first, second);
        assert_eq!(WFE_PROTOCOL_VERSION, 6);
        assert_eq!(protocol_schema_sha256(), WFE_PROTOCOL_V6_SCHEMA_SHA256);
        assert!(first.contains("export type ICommandRequest"));
        assert!(first.contains("cancel_id: string"));
        assert!(first.contains("history_entry_selected"));
        assert!(first.contains("read_only_files: boolean"));
        assert!(first.contains("export type FilesListRequest"));
        assert!(first.contains("export type FilesReadResponse"));
        assert!(first.contains("export type FilesErrorResponse"));
        assert!(first.contains("\"cli_locked\""));
        assert!(first.contains("export const COMMAND_ORDER"));
        assert!(first.contains("export const UI_ICON_GLYPHS"));
        assert!(first.contains("export type UiIconId = keyof typeof UI_ICON_GLYPHS"));
        assert!(first.contains("export const SPINNER_FRAMES"));
        assert!(first.contains("export const TOOL_SPINNER_FRAMES"));
        assert!(first.contains("export const THEME_CATALOG"));

        let icon_ids = crate::icons::WFE_UI_ICONS
            .iter()
            .map(|(id, _)| *id)
            .collect::<std::collections::BTreeSet<_>>();
        let icon_glyphs = crate::icons::WFE_UI_ICONS
            .iter()
            .map(|(_, glyph)| *glyph)
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(icon_ids.len(), crate::icons::WFE_UI_ICONS.len());
        assert_eq!(icon_glyphs.len(), crate::icons::WFE_UI_ICONS.len());
        assert!(
            crate::icons::WFE_UI_ICONS
                .iter()
                .all(|(id, glyph)| !id.is_empty() && glyph.chars().count() == 1)
        );
        for forbidden in [
            "api_key",
            "server_url",
            "provider_content",
            "provider_id",
            "session_directory_binding",
            "python_runtime_id",
            "current_session_dir",
            "debug_log",
            "logical_turn_id",
        ] {
            assert!(!first.contains(forbidden), "generated `{forbidden}`");
        }
    }
}
