#!/usr/bin/env python3
"""Derive the exact Rust embed/dependency list from the reviewed web manifest."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path, PurePosixPath
import tempfile

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "web/static/build-support/dist-assets.json"
OUTPUT = ROOT / "src/wfe/assets_manifest.rs"
HEADER = "// Generated by scripts/generate_web_asset_manifest.py; do not edit.\n"


def generated() -> bytes:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if set(manifest) != {"schema_version", "application_assets", "static_assets", "vendor_assets"} or manifest["schema_version"] != 2:
        raise ValueError("unexpected distribution manifest")
    paths = []
    for key, prefix in [("application_assets", ""), ("static_assets", ""), ("vendor_assets", "lib/")]:
        values = manifest[key]
        if not isinstance(values, list) or not all(isinstance(value, str) for value in values) or values != sorted(set(values)):
            raise ValueError("asset lists must be sorted and unique")
        for value in values:
            path = PurePosixPath(prefix + value)
            if path.is_absolute() or path.as_posix() != prefix + value or any(part in {".", ".."} for part in path.parts) or not all(character.isascii() and (character.isalnum() or character in "/._-") for character in str(path)):
                raise ValueError("noncanonical asset path")
            paths.append(str(path))
    if len(set(paths)) != len(paths):
        raise ValueError("cross-category asset collision")
    expected = set(paths)
    dist = ROOT / "web/dist"
    if dist.is_symlink() or not dist.is_dir():
        raise ValueError("distribution must be a regular directory")
    actual = set()
    for path in dist.rglob("*"):
        if path.is_symlink():
            raise ValueError("distribution contains a symlink")
        if path.is_file():
            actual.add(path.relative_to(dist).as_posix())
        elif not path.is_dir():
            raise ValueError("distribution contains a special file")
    if actual != expected:
        raise ValueError("build web/dist before updating the Rust asset manifest")
    return (HEADER + "tracked_assets!(\n" + "".join(f'    "{path}",\n' for path in sorted(paths)) + ");\n").encode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="update the generated Rust asset list")
    args = parser.parse_args()
    content = generated()
    if OUTPUT.is_symlink():
        raise ValueError("refusing a symlink Rust asset manifest")
    previous = OUTPUT.read_bytes() if OUTPUT.exists() else None
    if previous == content:
        print("Rust embedded asset manifest matches the exact distribution")
        return
    if not args.write:
        raise ValueError("Rust embedded asset manifest is stale; run build-web.sh")
    if previous is not None and not previous.startswith(HEADER.encode("utf-8")):
        raise ValueError("refusing to replace a non-generated Rust asset manifest")
    with tempfile.NamedTemporaryFile(dir=OUTPUT.parent, prefix=".assets_manifest-", delete=False) as temporary:
        pending = Path(temporary.name)
        try:
            temporary.write(content)
            temporary.flush()
            os.fchmod(temporary.fileno(), 0o644)
            os.fsync(temporary.fileno())
            pending.replace(OUTPUT)
        finally:
            pending.unlink(missing_ok=True)
    print("Updated the exact Rust embedded asset manifest")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, TypeError) as error:
        raise SystemExit(f"generate_web_asset_manifest.py: {error}") from error
