pub const MODEL: &str = "󰚩";      // nf-md-robot
pub const SERVER: &str = "󰒋";     // nf-md-server
pub const TOKENS: &str = "󰌨";     // nf-md-poker_chip
pub const COMMAND: &str = "󰘳";    // nf-md-command
pub const THEME: &str = "󰔎";      // nf-md-palette
pub const TRASH: &str = "󰩹";      // nf-md-trash_can
pub const QUIT: &str = "󰗼";       // nf-md-exit_to_app
pub const WARNING: &str = "󰀦";    // nf-md-alert
pub const SUCCESS: &str = "󰄬";    // nf-md-check
pub const PROCESSING: &str = "󱑔"; // nf-md-progress_clock
pub const SHELL: &str = "󱆃";      // nf-md-bash
pub const WEATHER: &str = "󰖐";     // nf-md-weather_cloudy
pub const CALC: &str = "󰃬";        // nf-md-calculator
pub const SEARCH: &str = "󰍉";      // nf-md-magnify
pub const INPUT: &str = "󰌑";       // nf-md-keyboard_return
pub const OUTPUT: &str = "󰗊";      // nf-md-message_text
pub const DEBUG: &str = "󰃤";       // nf-md-bug
pub const PATH: &str = "󰝰";        // nf-md-folder
pub const GIT: &str = "󰊢";         // nf-md-git
pub const SPINNER: &[&str] = &["◰", "◳", "◲", "◱"];
pub const TOOL_SPINNER: &[&str] = &["⢎ ", "⠎⠁", "⠊⠑", "⠈⠱", " ⠱", "⠠⠰", "⠄⠄", "⠆⠄"];
